int layer0[44] = {

        KEY_P, KEY_O, KEY_I, KEY_U, KEY_Y, KEY_0, KEY_T, KEY_R, KEY_E, KEY_W, KEY_Q,

        KEY_SEMICOLON, KEY_L, KEY_K, KEY_J, KEY_H, KEY_0, KEY_G, KEY_F, KEY_D, KEY_S, KEY_A,

        KEY_SLASH, KEY_PERIOD, KEY_COMMA, KEY_M, KEY_N, KEYBOARD_LEFT_ALT, KEY_B, KEY_V, KEY_C, KEY_X, KEY_Z,

        KEY_ENTER, KEY_QUOTE, PRE_FUNCTION(1), KEYBOARD_LEFT_CTRL, KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_GUI, KEY_MINUS, KEY_TAB, KEY_ESC

};

int layer1[44] = {

        SHIFT(KEY_8), KEY_9, KEY_8, KEY_7, KEY_PAGE_UP, KEY_0, SHIFT(KEY_BACKSLASH), SHIFT(KEY_RIGHT_BRACE), SHIFT(KEY_LEFT_BRACE), SHIFT(KEY_2), SHIFT(KEY_1),

        SHIFT(KEY_EQUAL), KEY_6, KEY_5, KEY_4, KEY_PAGE_DOWN, KEY_0, KEY_TILDE, SHIFT(KEY_0), SHIFT(KEY_9), SHIFT(KEY_4), SHIFT(KEY_3),

        KEY_BACKSLASH, KEY_3, KEY_2, KEY_1, SHIFT(KEY_7), KEYBOARD_LEFT_ALT, SHIFT(KEY_TILDE), KEY_RIGHT_BRACE, KEY_LEFT_BRACE, SHIFT(KEY_6), SHIFT(KEY_5),

        KEY_EQUAL, KEY_0, PRE_FUNCTION(1), KEYBOARD_LEFT_CTRL, KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_GUI, KEY_MINUS, SHIFT(KEY_INSERT), FUNCTION(2)

};

// layer2.h reversed
int layer2[44] = {

        KEY_F10, KEY_F9, KEY_F8, KEY_F7, KEY_UP, KEY_0, KEY_PAGE_UP, KEY_END, KEY_UP, KEY_HOME, KEY_INSERT,

        KEY_F11, KEY_F6, KEY_F5, KEY_F4, KEY_DOWN, KEY_0, KEY_PAGE_DOWN, KEY_RIGHT, KEY_DOWN, KEY_LEFT, KEY_DELETE,

        KEY_F12, KEY_F3, KEY_F2, KEY_F1, 0, KEYBOARD_LEFT_ALT, 0, 0, 0, 0, 0,

        FUNCTION(0), 0, PRE_FUNCTION(1), KEYBOARD_LEFT_CTRL, KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_GUI, 0, FUNCTION(3), 0

};

int *layers[] = {layer0, layer1, layer2};

#include "layout_common.h"
